name: Build

on: [pull_request, push]

permissions: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        java:
          - 11
          - 17
          - 21
    steps:
      - name: Check out
        with:
          persist-credentials: false
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: "gradle"
      - name: Setup Gradle and run build
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
        env:
          CHECK_GENERATED_FILES: true
          SMOKE_TEST_JAVA_VERSION: ${{ matrix.java }} # the smoke tests will pick this up